version: '2'
services:
    kapp-app:
        image: kapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kapp-postgresql:5432/kapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kapp-postgresql:
        extends:
            file: postgresql.yml
            service: kapp-postgresql
