version: '2'
services:
    kapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/kapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=kapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
